/** Ed25519 public key of the catalog publisher (generated by scripts/gen-catalog-key.mjs; the private key lives in the macOS Keychain). */
export const CATALOG_PUBLIC_KEY = "b70e53b98bc4fad7eae3919e7fcd04b5c421aa67c989f9cb729c43a224391798";
