/** Ed25519 public key for desktop licence keys (generated by scripts/gen-licence-key.mjs; the private seed lives in the macOS Keychain). */
export const LICENCE_PUBLIC_KEY = "9be16438f08d756cc08dfb4e9bdd73db5dfc249da2ab35f85368614fa2c4585f";
