const fs = require("fs");
const path = require("path");
const { withAppBuildGradle, withDangerousMod, withSettingsGradle } = require("expo/config-plugins");

/* Play Asset Delivery (spec §5.1, §5.4): models reach Android through Play, never through a socket the app opens. */
const ASSET_DELIVERY = "com.google.android.play:asset-delivery:2.3.0";

/**
 * Every pack becomes a Gradle asset-pack module `android/<name>` at prebuild time; its assets are symlinked from
 * INBORN_MODELS_DIR (default `<repo>/.models`, gitignored) so no model is ever committed or copied.
 * A pack whose source file is missing is skipped with a warning, and the app then falls back to the document directory.
 *
 * @typedef {{ name: string; deliveryType: "install-time" | "fast-follow" | "on-demand"; assets: Record<string, string> }} Pack
 * @param {import("expo/config").ExpoConfig} config
 * @param {{ packs: Pack[] }} props
 */
function withAssetPacks(config, { packs }) {
  config = withDangerousMod(config, [
    "android",
    (config) => {
      const android = path.join(config.modRequest.platformProjectRoot);
      for (const pack of resolvePacks(config.modRequest.projectRoot, packs)) {
        const assetsDir = path.join(android, pack.name, "src", "main", "assets");
        fs.mkdirSync(assetsDir, { recursive: true });
        fs.writeFileSync(path.join(android, pack.name, "build.gradle"), packBuildGradle(pack));
        for (const [asset, source] of Object.entries(pack.sources)) {
          const link = path.join(assetsDir, asset);
          fs.rmSync(link, { force: true });
          fs.symlinkSync(source, link);
        }
      }
      return config;
    },
  ]);

  config = withSettingsGradle(config, (config) => {
    for (const pack of resolvePacks(config.modRequest.projectRoot, packs)) {
      const line = `include ':${pack.name}'`;
      if (!config.modResults.contents.includes(line)) config.modResults.contents += `\n${line}\n`;
    }
    return config;
  });

  config = withAppBuildGradle(config, (config) => {
    let contents = config.modResults.contents;
    const names = resolvePacks(config.modRequest.projectRoot, packs).map((p) => `":${p.name}"`);
    if (names.length && !contents.includes("assetPacks = [")) {
      contents = contents.replace(/^android \{\n/m, `android {\n    assetPacks = [${names.join(", ")}]\n`);
    }
    if (!contents.includes(ASSET_DELIVERY)) {
      contents = contents.replace(/^dependencies \{\n/m, `dependencies {\n    implementation("${ASSET_DELIVERY}")\n`);
    }
    config.modResults.contents = contents;
    return config;
  });

  return config;
}

/** @param {Pack[]} packs @returns {(Pack & { sources: Record<string, string> })[]} */
function resolvePacks(projectRoot, packs) {
  const modelsDir = process.env.INBORN_MODELS_DIR || path.join(projectRoot, "..", "..", ".models");
  const ready = [];
  for (const pack of packs) {
    const sources = {};
    const missing = [];
    for (const [asset, file] of Object.entries(pack.assets)) {
      const source = path.join(modelsDir, file);
      if (fs.existsSync(source)) sources[asset] = source;
      else missing.push(source);
    }
    if (missing.length) {
      console.warn(`withAssetPacks: skipping ${pack.name} (missing ${missing.join(", ")}; set INBORN_MODELS_DIR)`);
      continue;
    }
    ready.push({ ...pack, sources });
  }
  return ready;
}

function packBuildGradle(pack) {
  return `// Generated by plugins/withAssetPacks.js at prebuild; do not edit.
apply plugin: 'com.android.asset-pack'

assetPack {
    packName = "${pack.name}"
    dynamicDelivery {
        deliveryType = "${pack.deliveryType}"
    }
}
`;
}

module.exports = withAssetPacks;
